version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - $HOME/docker/home-assistant/config:/config:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      - TZ=Europe/Amsterdam
    depends_on:
      - mariadb
    network_mode: host
    privileged: true
    
 
  esphome:
    container_name: esphome
    image: esphome/esphome:latest
    volumes:
      - $HOME/docker/esphome:/config:rw
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    restart: always
    
  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb:latest
    volumes:
      - $HOME/docker/mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    network_mode: bridge
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=homeassistant
      - MYSQL_ROOT_PASSWORD=testpassword
      - MYSQL_USER=homeassistant
      - MYSQL_PASSWORD=testuserpassword
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
    restart: always

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    network_mode: bridge
    labels:
      - watchtower
