version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - $HOME/docker/home-assistant/config:/config:rw
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      - TZ=Europe/Amsterdam
    depends_on:
      - mariadb
    network_mode: host
    privileged: true
    
  samba:
    image: dperson/samba
    container_name: samba
    restart: always
    stdin_open: true
    tty: true
    environment:
      TZ: Europe/Amsterdam

      # advertise shares, default: true, or false (open ports 137, 138)
      NMBD: "true"

      # add a single user. If you need more, use command instead of environment
      # required arg: "<username>;<passwd>"
      # <username> for user
      # <password> for user
      # [ID] for user, default: ""
      # [group] for user, default: ""
      USER: "yourname;password"

      # set the UID for the samba share, default: ""
      USERID: "0"

      # set the GID for the samba share, default: ""
      GROUPID: "0"

      # add a single share. If you need more, use command instead of environment
      # required arg: "<name>;</path>"
      # <share_name>;
      # <path_to_share>;
      # [browsable] default:'yes' or 'no';
      # [read_only] default:'yes' or 'no';
      # [guest]: default: 'yes' or 'no';
      # [users]: default: 'all' or list of allowed users;
      # [admins] default: 'none' or list of admin users;
      # [writelist] default: 'none' or list of users that can write to read-only share;
      # [comment] default: 'none' or description of share
      SHARE: "share;/home/stijn;yes;no;no;stijn;'none';'none';'Raspberry'"

      # workgroup/domain name for share default: "MYGROUP"
      WORKGROUP: "Homeserver"

      # if set, disables recycle bin for shares
      RECYCLE: ""

      # if set, disables SMB2 minimum version
      # SMB: ""

    networks:
      - default
    ports:
      - "137:137/udp" # required to advertise shares (NMBD)
      - "138:138/udp" # required to advertise shares (NMBD)
      - "139:139/tcp" # default smb port
      - "445:445/tcp" # default smb port
    read_only: false
    tmpfs:
      - /tmp
    volumes:
      - /home/stijn:/mnt:z # :z allows share to be used by multiple containers
    
    
  ha-dockermon:
    container_name: ha-dockermon
    image: philhawthorne/ha-dockermon
    volumes:
      - $HOME/docker/ha-dockermon:/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    network_mode: bridge
    ports:
      - 8126:8126
    depends_on:
      - homeassistant
    restart: always
    
 
  esphome: #Web port: 6052
    container_name: esphome
    image: esphome/esphome:latest
    volumes:
      - $HOME/docker/esphome:/config:rw
      - /etc/localtime:/etc/localtime:ro
    network_mode: host # Host is required for mDNS discovery.
    restart: always
    
  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb:latest
    volumes:
      - $HOME/docker/mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    network_mode: bridge
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=homeassistant
      - MYSQL_ROOT_PASSWORD=testpassword
      - MYSQL_USER=homeassistant
      - MYSQL_PASSWORD=testuserpassword
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
    restart: always


  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    network_mode: bridge
    labels:
      - watchtower
